version: '3'

services:
  database:
    image: 'mongo'
    container_name: 'mongo_chat'
    environment:
      - MONGO_INITDB_DATABASE=chat
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'